/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found-route'
import { Route as LogoutRouteImport } from './routes/logout-route'
import { Route as LoginRouteImport } from './routes/login-route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthMyBookingsRouteImport } from './routes/_auth.my-bookings-route'
import { Route as AuthHomeRouteImport } from './routes/_auth.home-route'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin-route'

// Create/Update Routes

const NotFoundRouteRoute = NotFoundRouteImport.update({
  id: '/not-found-route',
  path: '/not-found-route',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRouteRoute = LogoutRouteImport.update({
  id: '/logout-route',
  path: '/logout-route',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login-route',
  path: '/login-route',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthMyBookingsRouteRoute = AuthMyBookingsRouteImport.update({
  id: '/_auth/my-bookings-route',
  path: '/my-bookings-route',
  getParentRoute: () => rootRoute,
} as any)

const AuthHomeRouteRoute = AuthHomeRouteImport.update({
  id: '/_auth/home-route',
  path: '/home-route',
  getParentRoute: () => rootRoute,
} as any)

const AuthAdminRouteRoute = AuthAdminRouteImport.update({
  id: '/_auth/admin-route',
  path: '/admin-route',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login-route': {
      id: '/login-route'
      path: '/login-route'
      fullPath: '/login-route'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/logout-route': {
      id: '/logout-route'
      path: '/logout-route'
      fullPath: '/logout-route'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/not-found-route': {
      id: '/not-found-route'
      path: '/not-found-route'
      fullPath: '/not-found-route'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/admin-route': {
      id: '/_auth/admin-route'
      path: '/admin-route'
      fullPath: '/admin-route'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/home-route': {
      id: '/_auth/home-route'
      path: '/home-route'
      fullPath: '/home-route'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/my-bookings-route': {
      id: '/_auth/my-bookings-route'
      path: '/my-bookings-route'
      fullPath: '/my-bookings-route'
      preLoaderRoute: typeof AuthMyBookingsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-route': typeof LoginRouteRoute
  '/logout-route': typeof LogoutRouteRoute
  '/not-found-route': typeof NotFoundRouteRoute
  '/admin-route': typeof AuthAdminRouteRoute
  '/home-route': typeof AuthHomeRouteRoute
  '/my-bookings-route': typeof AuthMyBookingsRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-route': typeof LoginRouteRoute
  '/logout-route': typeof LogoutRouteRoute
  '/not-found-route': typeof NotFoundRouteRoute
  '/admin-route': typeof AuthAdminRouteRoute
  '/home-route': typeof AuthHomeRouteRoute
  '/my-bookings-route': typeof AuthMyBookingsRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login-route': typeof LoginRouteRoute
  '/logout-route': typeof LogoutRouteRoute
  '/not-found-route': typeof NotFoundRouteRoute
  '/_auth/admin-route': typeof AuthAdminRouteRoute
  '/_auth/home-route': typeof AuthHomeRouteRoute
  '/_auth/my-bookings-route': typeof AuthMyBookingsRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-route'
    | '/logout-route'
    | '/not-found-route'
    | '/admin-route'
    | '/home-route'
    | '/my-bookings-route'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-route'
    | '/logout-route'
    | '/not-found-route'
    | '/admin-route'
    | '/home-route'
    | '/my-bookings-route'
  id:
    | '__root__'
    | '/'
    | '/login-route'
    | '/logout-route'
    | '/not-found-route'
    | '/_auth/admin-route'
    | '/_auth/home-route'
    | '/_auth/my-bookings-route'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRouteRoute: typeof LoginRouteRoute
  LogoutRouteRoute: typeof LogoutRouteRoute
  NotFoundRouteRoute: typeof NotFoundRouteRoute
  AuthAdminRouteRoute: typeof AuthAdminRouteRoute
  AuthHomeRouteRoute: typeof AuthHomeRouteRoute
  AuthMyBookingsRouteRoute: typeof AuthMyBookingsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRouteRoute: LoginRouteRoute,
  LogoutRouteRoute: LogoutRouteRoute,
  NotFoundRouteRoute: NotFoundRouteRoute,
  AuthAdminRouteRoute: AuthAdminRouteRoute,
  AuthHomeRouteRoute: AuthHomeRouteRoute,
  AuthMyBookingsRouteRoute: AuthMyBookingsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login-route",
        "/logout-route",
        "/not-found-route",
        "/_auth/admin-route",
        "/_auth/home-route",
        "/_auth/my-bookings-route"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login-route": {
      "filePath": "login-route.tsx"
    },
    "/logout-route": {
      "filePath": "logout-route.tsx"
    },
    "/not-found-route": {
      "filePath": "not-found-route.tsx"
    },
    "/_auth/admin-route": {
      "filePath": "_auth.admin-route.tsx"
    },
    "/_auth/home-route": {
      "filePath": "_auth.home-route.tsx"
    },
    "/_auth/my-bookings-route": {
      "filePath": "_auth.my-bookings-route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
